<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Moon;

class MoonSeeder extends Seeder
{
    public function run(): void
    {
        // Earth's Moon (Planet ID 3 - Earth in Sol System)
        Moon::create([
            'moon_name' => 'Moon',
            'moon_desc' => 'Earth only satellite',
            'moon_type' => 'rocky',
            'moon_gravity' => 1.62,
            'moon_surface_temp' => 290,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.0549,
            'moon_apogee' => 405,
            'moon_perigee' => 363,
            'moon_orbital_inclination' => 5.145,
            'moon_average_distance' => 384,
            'moon_orbital_period' => 27.3,
            'moon_inclination_angle' => 6.687,
            'moon_rotation_period' => 27.3,
            'moon_mass' => 73,
            'moon_diameter' => 3474,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 3,
            'user_id' => 2,
        ]);

        // Mars moons (Planet ID 4 - Mars in Sol System)
        Moon::create([
            'moon_name' => 'Phobos',
            'moon_desc' => 'Largest moon of Mars',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.0057,
            'moon_surface_temp' => 230,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.0151,
            'moon_apogee' => 9517,
            'moon_perigee' => 9234,
            'moon_orbital_inclination' => 1.093,
            'moon_average_distance' => 9376,
            'moon_orbital_period' => 0.32,
            'moon_inclination_angle' => 0.046,
            'moon_rotation_period' => 0.32,
            'moon_mass' => 0.011,
            'moon_diameter' => 22,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 4,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Deimos',
            'moon_desc' => 'Smaller moon of Mars',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.003,
            'moon_surface_temp' => 230,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.0002,
            'moon_apogee' => 23471,
            'moon_perigee' => 23463,
            'moon_orbital_inclination' => 0.93,
            'moon_average_distance' => 23467,
            'moon_orbital_period' => 1.26,
            'moon_inclination_angle' => 0.32,
            'moon_rotation_period' => 1.26,
            'moon_mass' => 0.002,
            'moon_diameter' => 12,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 4,
            'user_id' => 2,
        ]);

        // Jupiter moons (Planet ID 5 - Jupiter in Sol System)
        Moon::create([
            'moon_name' => 'Io',
            'moon_desc' => 'Volcanic moon of Jupiter',
            'moon_type' => 'rocky',
            'moon_gravity' => 1.796,
            'moon_surface_temp' => 110,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.0041,
            'moon_apogee' => 423400,
            'moon_perigee' => 420000,
            'moon_orbital_inclination' => 2.21,
            'moon_average_distance' => 421700,
            'moon_orbital_period' => 1.77,
            'moon_inclination_angle' => 0.05,
            'moon_rotation_period' => 1.77,
            'moon_mass' => 89,
            'moon_diameter' => 3643,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 5,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Europa',
            'moon_desc' => 'Icy moon of Jupiter',
            'moon_type' => 'icy',
            'moon_gravity' => 1.314,
            'moon_surface_temp' => 110,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.009,
            'moon_apogee' => 676938,
            'moon_perigee' => 664862,
            'moon_orbital_inclination' => 1.79,
            'moon_average_distance' => 670900,
            'moon_orbital_period' => 3.55,
            'moon_inclination_angle' => 0.1,
            'moon_rotation_period' => 3.55,
            'moon_mass' => 48,
            'moon_diameter' => 3121,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 5,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Ganymede',
            'moon_desc' => 'Largest moon in solar system',
            'moon_type' => 'icy',
            'moon_gravity' => 1.428,
            'moon_surface_temp' => 90,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.0013,
            'moon_apogee' => 1071600,
            'moon_perigee' => 1069200,
            'moon_orbital_inclination' => 2.21,
            'moon_average_distance' => 1070400,
            'moon_orbital_period' => 7.15,
            'moon_inclination_angle' => 0.2,
            'moon_rotation_period' => 7.15,
            'moon_mass' => 148,
            'moon_diameter' => 5268,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 5,
            'user_id' => 2,
        ]);

        // Saturn moons (Planet ID 6 - Saturn in Sol System)
        Moon::create([
            'moon_name' => 'Titan',
            'moon_desc' => 'Largest moon of Saturn',
            'moon_type' => 'icy',
            'moon_gravity' => 1.352,
            'moon_surface_temp' => 90,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.0288,
            'moon_apogee' => 1257060,
            'moon_perigee' => 1186680,
            'moon_orbital_inclination' => 0.34,
            'moon_average_distance' => 1221830,
            'moon_orbital_period' => 15.95,
            'moon_inclination_angle' => 0.34,
            'moon_rotation_period' => 15.95,
            'moon_mass' => 135,
            'moon_diameter' => 5149,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 6,
            'user_id' => 2,
        ]);

        // Kepler-1b moons (Planet ID 9)
        Moon::create([
            'moon_name' => 'Kepler-1b-I',
            'moon_desc' => 'First moon of Kepler-1b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.8,
            'moon_surface_temp' => 590,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.02,
            'moon_apogee' => 15,
            'moon_perigee' => 14,
            'moon_orbital_inclination' => 1.5,
            'moon_average_distance' => 15,
            'moon_orbital_period' => 2.1,
            'moon_inclination_angle' => 0.5,
            'moon_rotation_period' => 2.1,
            'moon_mass' => 0.8,
            'moon_diameter' => 890,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 9,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-1b-II',
            'moon_desc' => 'Second moon of Kepler-1b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.6,
            'moon_surface_temp' => 580,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.04,
            'moon_apogee' => 25,
            'moon_perigee' => 23,
            'moon_orbital_inclination' => 2.8,
            'moon_average_distance' => 24,
            'moon_orbital_period' => 4.2,
            'moon_inclination_angle' => 1.2,
            'moon_rotation_period' => 4.2,
            'moon_mass' => 0.5,
            'moon_diameter' => 720,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 9,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-1b-III',
            'moon_desc' => 'Third moon of Kepler-1b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.4,
            'moon_surface_temp' => 570,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.06,
            'moon_apogee' => 38,
            'moon_perigee' => 35,
            'moon_orbital_inclination' => 4.1,
            'moon_average_distance' => 37,
            'moon_orbital_period' => 7.8,
            'moon_inclination_angle' => 2.1,
            'moon_rotation_period' => 7.8,
            'moon_mass' => 0.3,
            'moon_diameter' => 580,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 9,
            'user_id' => 2,
        ]);

        // Kepler-2b moons (Planet ID 10)
        Moon::create([
            'moon_name' => 'Kepler-2b-I',
            'moon_desc' => 'First moon of Kepler-2b',
            'moon_type' => 'rocky',
            'moon_gravity' => 1.2,
            'moon_surface_temp' => 510,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.03,
            'moon_apogee' => 28,
            'moon_perigee' => 26,
            'moon_orbital_inclination' => 1.8,
            'moon_average_distance' => 27,
            'moon_orbital_period' => 3.5,
            'moon_inclination_angle' => 0.8,
            'moon_rotation_period' => 3.5,
            'moon_mass' => 1.5,
            'moon_diameter' => 1200,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 10,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-2b-II',
            'moon_desc' => 'Second moon of Kepler-2b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.9,
            'moon_surface_temp' => 510,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.05,
            'moon_apogee' => 42,
            'moon_perigee' => 38,
            'moon_orbital_inclination' => 3.2,
            'moon_average_distance' => 40,
            'moon_orbital_period' => 6.8,
            'moon_inclination_angle' => 1.5,
            'moon_rotation_period' => 6.8,
            'moon_mass' => 1.1,
            'moon_diameter' => 980,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 10,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-2b-III',
            'moon_desc' => 'Third moon of Kepler-2b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.7,
            'moon_surface_temp' => 490,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.08,
            'moon_apogee' => 58,
            'moon_perigee' => 52,
            'moon_orbital_inclination' => 5.1,
            'moon_average_distance' => 55,
            'moon_orbital_period' => 12.4,
            'moon_inclination_angle' => 2.8,
            'moon_rotation_period' => 12.4,
            'moon_mass' => 0.8,
            'moon_diameter' => 850,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 10,
            'user_id' => 2,
        ]);

        // Kepler-3b moons (Planet ID 11)
        Moon::create([
            'moon_name' => 'Kepler-3b-I',
            'moon_desc' => 'First moon of Kepler-3b',
            'moon_type' => 'icy',
            'moon_gravity' => 1.5,
            'moon_surface_temp' => 280,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.02,
            'moon_apogee' => 35,
            'moon_perigee' => 33,
            'moon_orbital_inclination' => 1.2,
            'moon_average_distance' => 34,
            'moon_orbital_period' => 4.2,
            'moon_inclination_angle' => 0.6,
            'moon_rotation_period' => 4.2,
            'moon_mass' => 2.1,
            'moon_diameter' => 1450,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 11,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-3b-II',
            'moon_desc' => 'Second moon of Kepler-3b',
            'moon_type' => 'icy',
            'moon_gravity' => 1.8,
            'moon_surface_temp' => 275,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.04,
            'moon_apogee' => 52,
            'moon_perigee' => 48,
            'moon_orbital_inclination' => 2.5,
            'moon_average_distance' => 50,
            'moon_orbital_period' => 8.1,
            'moon_inclination_angle' => 1.3,
            'moon_rotation_period' => 8.1,
            'moon_mass' => 2.8,
            'moon_diameter' => 1680,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 11,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-3b-III',
            'moon_desc' => 'Third moon of Kepler-3b',
            'moon_type' => 'icy',
            'moon_gravity' => 1.1,
            'moon_surface_temp' => 270,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.06,
            'moon_apogee' => 78,
            'moon_perigee' => 72,
            'moon_orbital_inclination' => 3.8,
            'moon_average_distance' => 75,
            'moon_orbital_period' => 15.2,
            'moon_inclination_angle' => 2.1,
            'moon_rotation_period' => 15.2,
            'moon_mass' => 1.6,
            'moon_diameter' => 1250,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 11,
            'user_id' => 2,
        ]);

        // Kepler-4b moons (Planet ID 12)
        Moon::create([
            'moon_name' => 'Kepler-4b-I',
            'moon_desc' => 'First moon of Kepler-4b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.9,
            'moon_surface_temp' => 250,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.05,
            'moon_apogee' => 22,
            'moon_perigee' => 20,
            'moon_orbital_inclination' => 2.1,
            'moon_average_distance' => 21,
            'moon_orbital_period' => 2.8,
            'moon_inclination_angle' => 1.1,
            'moon_rotation_period' => 2.8,
            'moon_mass' => 0.9,
            'moon_diameter' => 920,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 12,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-4b-II',
            'moon_desc' => 'Second moon of Kepler-4b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.6,
            'moon_surface_temp' => 240,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.07,
            'moon_apogee' => 35,
            'moon_perigee' => 31,
            'moon_orbital_inclination' => 4.2,
            'moon_average_distance' => 33,
            'moon_orbital_period' => 5.6,
            'moon_inclination_angle' => 2.3,
            'moon_rotation_period' => 5.6,
            'moon_mass' => 0.6,
            'moon_diameter' => 750,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 12,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-4b-III',
            'moon_desc' => 'Third moon of Kepler-4b',
            'moon_type' => 'rocky',
            'moon_gravity' => 0.4,
            'moon_surface_temp' => 230,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.09,
            'moon_apogee' => 52,
            'moon_perigee' => 46,
            'moon_orbital_inclination' => 6.1,
            'moon_average_distance' => 49,
            'moon_orbital_period' => 10.8,
            'moon_inclination_angle' => 3.5,
            'moon_rotation_period' => 10.8,
            'moon_mass' => 0.4,
            'moon_diameter' => 620,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 12,
            'user_id' => 2,
        ]);

        // Kepler-5b moons (Planet ID 13)
        Moon::create([
            'moon_name' => 'Kepler-5b-I',
            'moon_desc' => 'First moon of Kepler-5b',
            'moon_type' => 'icy',
            'moon_gravity' => 2.1,
            'moon_surface_temp' => 180,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.03,
            'moon_apogee' => 85,
            'moon_perigee' => 82,
            'moon_orbital_inclination' => 1.5,
            'moon_average_distance' => 84,
            'moon_orbital_period' => 12.5,
            'moon_inclination_angle' => 0.8,
            'moon_rotation_period' => 12.5,
            'moon_mass' => 5.2,
            'moon_diameter' => 2180,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 13,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-5b-II',
            'moon_desc' => 'Second moon of Kepler-5b',
            'moon_type' => 'icy',
            'moon_gravity' => 1.8,
            'moon_surface_temp' => 160,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.05,
            'moon_apogee' => 128,
            'moon_perigee' => 122,
            'moon_orbital_inclination' => 2.8,
            'moon_average_distance' => 125,
            'moon_orbital_period' => 24.2,
            'moon_inclination_angle' => 1.5,
            'moon_rotation_period' => 24.2,
            'moon_mass' => 4.1,
            'moon_diameter' => 1980,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 13,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-5b-III',
            'moon_desc' => 'Third moon of Kepler-5b',
            'moon_type' => 'icy',
            'moon_gravity' => 1.4,
            'moon_surface_temp' => 165,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.08,
            'moon_apogee' => 185,
            'moon_perigee' => 168,
            'moon_orbital_inclination' => 4.5,
            'moon_average_distance' => 177,
            'moon_orbital_period' => 45.8,
            'moon_inclination_angle' => 2.8,
            'moon_rotation_period' => 45.8,
            'moon_mass' => 3.2,
            'moon_diameter' => 1720,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 13,
            'user_id' => 2,
        ]);

        // Kepler-6b moons (Planet ID 14)
        Moon::create([
            'moon_name' => 'Kepler-6b-I',
            'moon_desc' => 'First moon of Kepler-6b',
            'moon_type' => 'icy',
            'moon_gravity' => 3.2,
            'moon_surface_temp' => 130,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.02,
            'moon_apogee' => 195,
            'moon_perigee' => 192,
            'moon_orbital_inclination' => 1.2,
            'moon_average_distance' => 194,
            'moon_orbital_period' => 28.5,
            'moon_inclination_angle' => 0.6,
            'moon_rotation_period' => 28.5,
            'moon_mass' => 12.8,
            'moon_diameter' => 3250,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-6b-II',
            'moon_desc' => 'Second moon of Kepler-6b',
            'moon_type' => 'icy',
            'moon_gravity' => 2.8,
            'moon_surface_temp' => 130,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.04,
            'moon_apogee' => 295,
            'moon_perigee' => 285,
            'moon_orbital_inclination' => 2.1,
            'moon_average_distance' => 290,
            'moon_orbital_period' => 52.8,
            'moon_inclination_angle' => 1.2,
            'moon_rotation_period' => 52.8,
            'moon_mass' => 9.5,
            'moon_diameter' => 2890,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-6b-III',
            'moon_desc' => 'Third moon of Kepler-6b',
            'moon_type' => 'icy',
            'moon_gravity' => 2.2,
            'moon_surface_temp' => 120,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.07,
            'moon_apogee' => 425,
            'moon_perigee' => 395,
            'moon_orbital_inclination' => 3.8,
            'moon_average_distance' => 410,
            'moon_orbital_period' => 95.2,
            'moon_inclination_angle' => 2.1,
            'moon_rotation_period' => 95.2,
            'moon_mass' => 7.2,
            'moon_diameter' => 2580,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        // Kepler-7b moons (Planet ID 15)
        Moon::create([
            'moon_name' => 'Kepler-7b-I',
            'moon_desc' => 'First moon of Kepler-7b',
            'moon_type' => 'icy',
            'moon_gravity' => 3.2,
            'moon_surface_temp' => 140,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.02,
            'moon_apogee' => 195,
            'moon_perigee' => 192,
            'moon_orbital_inclination' => 1.2,
            'moon_average_distance' => 194,
            'moon_orbital_period' => 28.5,
            'moon_inclination_angle' => 0.6,
            'moon_rotation_period' => 28.5,
            'moon_mass' => 12.8,
            'moon_diameter' => 3250,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-7b-II',
            'moon_desc' => 'Second moon of Kepler-7b',
            'moon_type' => 'icy',
            'moon_gravity' => 2.8,
            'moon_surface_temp' => 140,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.04,
            'moon_apogee' => 295,
            'moon_perigee' => 285,
            'moon_orbital_inclination' => 2.1,
            'moon_average_distance' => 290,
            'moon_orbital_period' => 52.8,
            'moon_inclination_angle' => 1.2,
            'moon_rotation_period' => 52.8,
            'moon_mass' => 9.5,
            'moon_diameter' => 2890,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-7b-III',
            'moon_desc' => 'Third moon of Kepler-7b',
            'moon_type' => 'icy',
            'moon_gravity' => 2.2,
            'moon_surface_temp' => 120,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.07,
            'moon_apogee' => 425,
            'moon_perigee' => 395,
            'moon_orbital_inclination' => 3.8,
            'moon_average_distance' => 410,
            'moon_orbital_period' => 95.2,
            'moon_inclination_angle' => 2.1,
            'moon_rotation_period' => 95.2,
            'moon_mass' => 7.2,
            'moon_diameter' => 2580,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        // Kepler-8b moons (Planet ID 16)
        Moon::create([
            'moon_name' => 'Kepler-8b-I',
            'moon_desc' => 'First moon of Kepler-8b',
            'moon_type' => 'icy',
            'moon_gravity' => 3.2,
            'moon_surface_temp' => 130,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.02,
            'moon_apogee' => 195,
            'moon_perigee' => 192,
            'moon_orbital_inclination' => 1.2,
            'moon_average_distance' => 194,
            'moon_orbital_period' => 28.5,
            'moon_inclination_angle' => 0.6,
            'moon_rotation_period' => 28.5,
            'moon_mass' => 12.8,
            'moon_diameter' => 3250,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-8b-II',
            'moon_desc' => 'Second moon of Kepler-8b',
            'moon_type' => 'icy',
            'moon_gravity' => 2.8,
            'moon_surface_temp' => 125,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.04,
            'moon_apogee' => 295,
            'moon_perigee' => 285,
            'moon_orbital_inclination' => 2.1,
            'moon_average_distance' => 290,
            'moon_orbital_period' => 52.8,
            'moon_inclination_angle' => 1.2,
            'moon_rotation_period' => 52.8,
            'moon_mass' => 9.5,
            'moon_diameter' => 2890,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);

        Moon::create([
            'moon_name' => 'Kepler-8b-III',
            'moon_desc' => 'Third moon of Kepler-8b',
            'moon_type' => 'icy',
            'moon_gravity' => 2.2,
            'moon_surface_temp' => 120,
            'moon_orbital_longitude' => 0.0,
            'moon_eccentricity' => 0.07,
            'moon_apogee' => 425,
            'moon_perigee' => 395,
            'moon_orbital_inclination' => 3.8,
            'moon_average_distance' => 410,
            'moon_orbital_period' => 95.2,
            'moon_inclination_angle' => 2.1,
            'moon_rotation_period' => 95.2,
            'moon_mass' => 7.2,
            'moon_diameter' => 2580,
            'moon_rings' => 0,
            'moon_initial_x' => 0,
            'moon_initial_y' => 0,
            'moon_initial_z' => 0,
            'planet_id' => 14,
            'user_id' => 2,
        ]);
    }
}