<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Planet;

class PlanetSeeder extends Seeder
{
    public function run(): void
    {
        // Mercury - Sol System
        Planet::create([
            'planet_name' => 'Mercury',
            'planet_desc' => 'The smallest planet of our solar system',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 3.7,
            'planet_surface_temp' => 430.0,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.206,
            'planet_apogee' => 69,
            'planet_perigee' => 46,
            'planet_orbital_inclination' => 7.0,
            'planet_average_distance' => 58,
            'planet_orbital_period' => 88,
            'planet_inclination_angle' => 0.034,
            'planet_rotation_period' => 1407,
            'planet_mass' => 330,
            'planet_diameter' => 4879,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Venus - Sol System
        Planet::create([
            'planet_name' => 'Venus',
            'planet_desc' => 'The hottest planet of our solar system',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 8.87,
            'planet_surface_temp' => 462.0,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.007,
            'planet_apogee' => 109,
            'planet_perigee' => 107,
            'planet_orbital_inclination' => 3.4,
            'planet_average_distance' => 108,
            'planet_orbital_period' => 225,
            'planet_inclination_angle' => 177.4,
            'planet_rotation_period' => 5832,
            'planet_mass' => 4867,
            'planet_diameter' => 12104,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Earth - Sol System
        Planet::create([
            'planet_name' => 'Earth',
            'planet_desc' => 'The blue planet',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 9.8,
            'planet_surface_temp' => 290,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.017,
            'planet_apogee' => 152,
            'planet_perigee' => 147,
            'planet_orbital_inclination' => 0.0,
            'planet_average_distance' => 150,
            'planet_orbital_period' => 365,
            'planet_inclination_angle' => 23.4,
            'planet_rotation_period' => 24,
            'planet_mass' => 5972,
            'planet_diameter' => 12756,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Mars - Sol System
        Planet::create([
            'planet_name' => 'Mars',
            'planet_desc' => 'The red planet',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 3.71,
            'planet_surface_temp' => 190.0,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.094,
            'planet_apogee' => 249,
            'planet_perigee' => 207,
            'planet_orbital_inclination' => 1.9,
            'planet_average_distance' => 228,
            'planet_orbital_period' => 687,
            'planet_inclination_angle' => 25.2,
            'planet_rotation_period' => 25,
            'planet_mass' => 642,
            'planet_diameter' => 6792,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Jupiter - Sol System
        Planet::create([
            'planet_name' => 'Jupiter',
            'planet_desc' => 'The largest planet',
            'planet_type' => 'gas',
            'planet_gravity' => 24.79,
            'planet_surface_temp' => 150.0,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.049,
            'planet_apogee' => 816,
            'planet_perigee' => 741,
            'planet_orbital_inclination' => 1.3,
            'planet_average_distance' => 778,
            'planet_orbital_period' => 4333,
            'planet_inclination_angle' => 3.1,
            'planet_rotation_period' => 10,
            'planet_mass' => 1898000,
            'planet_diameter' => 142984,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Saturn - Sol System
        Planet::create([
            'planet_name' => 'Saturn',
            'planet_desc' => 'The ringed planet',
            'planet_type' => 'gas',
            'planet_gravity' => 10.44,
            'planet_surface_temp' => 130.0,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.057,
            'planet_apogee' => 1514,
            'planet_perigee' => 1352,
            'planet_orbital_inclination' => 2.5,
            'planet_average_distance' => 1432,
            'planet_orbital_period' => 10759,
            'planet_inclination_angle' => 26.7,
            'planet_rotation_period' => 11,
            'planet_mass' => 568000,
            'planet_diameter' => 120536,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Uranus - Sol System
        Planet::create([
            'planet_name' => 'Uranus',
            'planet_desc' => 'The tilted ice giant',
            'planet_type' => 'ice',
            'planet_gravity' => 8.69,
            'planet_surface_temp' => 80.0,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.046,
            'planet_apogee' => 3003,
            'planet_perigee' => 2741,
            'planet_orbital_inclination' => 0.8,
            'planet_average_distance' => 2872,
            'planet_orbital_period' => 30589,
            'planet_inclination_angle' => 97.8,
            'planet_rotation_period' => 17,
            'planet_mass' => 86800,
            'planet_diameter' => 51118,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Neptune - Sol System
        Planet::create([
            'planet_name' => 'Neptune',
            'planet_desc' => 'The windiest planet',
            'planet_type' => 'ice',
            'planet_gravity' => 11.0,
            'planet_surface_temp' => 70,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.011,
            'planet_apogee' => 4545,
            'planet_perigee' => 4444,
            'planet_orbital_inclination' => 1.8,
            'planet_average_distance' => 4495,
            'planet_orbital_period' => 59800,
            'planet_inclination_angle' => 28.3,
            'planet_rotation_period' => 16,
            'planet_mass' => 102000,
            'planet_diameter' => 49528,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8002,
            'user_id' => 2,
        ]);

        // Kepler System - 8 planets
        Planet::create([
            'planet_name' => 'Kepler-1b',
            'planet_desc' => 'Rocky inner planet',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 4.2,
            'planet_surface_temp' => 660,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.12,
            'planet_apogee' => 45,
            'planet_perigee' => 38,
            'planet_orbital_inclination' => 2.1,
            'planet_average_distance' => 42,
            'planet_orbital_period' => 56,
            'planet_inclination_angle' => 12.5,
            'planet_rotation_period' => 28,
            'planet_mass' => 287,
            'planet_diameter' => 4200,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);

        Planet::create([
            'planet_name' => 'Kepler-2b',
            'planet_desc' => 'Hot Venus-like world',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 7.8,
            'planet_surface_temp' => 550.0,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.08,
            'planet_apogee' => 78,
            'planet_perigee' => 72,
            'planet_orbital_inclination' => 1.8,
            'planet_average_distance' => 75,
            'planet_orbital_period' => 98,
            'planet_inclination_angle' => 45.2,
            'planet_rotation_period' => 89,
            'planet_mass' => 3200,
            'planet_diameter' => 9800,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);

        Planet::create([
            'planet_name' => 'Kepler-3b',
            'planet_desc' => 'Ocean world in habitable zone',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 11.2,
            'planet_surface_temp' => 300,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.05,
            'planet_apogee' => 125,
            'planet_perigee' => 118,
            'planet_orbital_inclination' => 0.5,
            'planet_average_distance' => 122,
            'planet_orbital_period' => 187,
            'planet_inclination_angle' => 18.7,
            'planet_rotation_period' => 26,
            'planet_mass' => 4800,
            'planet_diameter' => 11200,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);

        Planet::create([
            'planet_name' => 'Kepler-4b',
            'planet_desc' => 'Desert world',
            'planet_type' => 'terrestrial',
            'planet_gravity' => 5.6,
            'planet_surface_temp' => 280,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.15,
            'planet_apogee' => 195,
            'planet_perigee' => 165,
            'planet_orbital_inclination' => 3.2,
            'planet_average_distance' => 180,
            'planet_orbital_period' => 312,
            'planet_inclination_angle' => 31.4,
            'planet_rotation_period' => 31,
            'planet_mass' => 1200,
            'planet_diameter' => 7800,
            'planet_rings' => 0,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);

        Planet::create([
            'planet_name' => 'Kepler-5b',
            'planet_desc' => 'Mini Neptune',
            'planet_type' => 'gas',
            'planet_gravity' => 18.5,
            'planet_surface_temp' => 180,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.08,
            'planet_apogee' => 385,
            'planet_perigee' => 355,
            'planet_orbital_inclination' => 2.7,
            'planet_average_distance' => 370,
            'planet_orbital_period' => 756,
            'planet_inclination_angle' => 8.9,
            'planet_rotation_period' => 14,
            'planet_mass' => 45000,
            'planet_diameter' => 28500,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);

        Planet::create([
            'planet_name' => 'Kepler-6b',
            'planet_desc' => 'Gas giant with storms',
            'planet_type' => 'gas',
            'planet_gravity' => 22.1,
            'planet_surface_temp' => 150,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.12,
            'planet_apogee' => 685,
            'planet_perigee' => 615,
            'planet_orbital_inclination' => 1.9,
            'planet_average_distance' => 650,
            'planet_orbital_period' => 1487,
            'planet_inclination_angle' => 15.6,
            'planet_rotation_period' => 12,
            'planet_mass' => 890000,
            'planet_diameter' => 78000,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);

        Planet::create([
            'planet_name' => 'Kepler-7b',
            'planet_desc' => 'Ice giant with methane clouds',
            'planet_type' => 'ice',
            'planet_gravity' => 12.8,
            'planet_surface_temp' => 100,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.09,
            'planet_apogee' => 1125,
            'planet_perigee' => 1045,
            'planet_orbital_inclination' => 0.8,
            'planet_average_distance' => 1085,
            'planet_orbital_period' => 3254,
            'planet_inclination_angle' => 78.3,
            'planet_rotation_period' => 18,
            'planet_mass' => 78000,
            'planet_diameter' => 52000,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);

        Planet::create([
            'planet_name' => 'Kepler-8b',
            'planet_desc' => 'Frozen outer world',
            'planet_type' => 'ice',
            'planet_gravity' => 9.7,
            'planet_surface_temp' => 50,
            'planet_orbital_longitude' => 0.0,
            'planet_eccentricity' => 0.18,
            'planet_apogee' => 1785,
            'planet_perigee' => 1485,
            'planet_orbital_inclination' => 4.5,
            'planet_average_distance' => 1635,
            'planet_orbital_period' => 6874,
            'planet_inclination_angle' => 42.1,
            'planet_rotation_period' => 22,
            'planet_mass' => 62000,
            'planet_diameter' => 48000,
            'planet_rings' => 1,
            'planet_initial_x' => 0,
            'planet_initial_y' => 0,
            'planet_initial_z' => 0,
            'solar_system_id' => 8003,
            'user_id' => 2,
        ]);
    }
}
